### ISSUE TITLE
After clicking destroy count not updated to 0 and not able to click Update button also ?

### ISSUE THREAD

**Issue by sivaprabug** [ecofic/course-vue-getting-started#1]
Hi @ecofic,
In this [module-01/initializing-an-instance-of-vue/example-03.html](https://github.com/ecofic/course-vue-getting-started/blob/master/src/module-01/initializing-an-instance-of-vue/example-03.html) 

- I clicked the button 5 times, then the values are updated like **Update Button Clicks: 5** 
- Then i click destroy button they value not coming to initial value 0 ? and After that i can able to click the Update button also?

Please explain the flow and my doubts.

FYI - 

![image](https://user-images.githubusercontent.com/2444608/27344977-ce4ed352-5605-11e7-9fd7-bbef0d5f4d18.png)

regards,
@gsivaprabu

**Comment by chadcampbell** [comment]
When a Vue instance is destroyed, it does not reset the data values to their initial values. Instead, when an instance is destroyed, it does things like tear down the bindings in the UI. That's why you do not see the value in the click count reset in the UI when you click the "Destroy" button. This is also the reason why "5" is still shown in the click counter.
